WHITESPACE = _{" " | "\n"}

oper = _{ suma | resta | mult | div}
    suma = { "+" }
    resta = { "-" }
    mult = { "*" }
    div = { "/" }


expr = { term ~ (oper ~ term)* }

term = _{ int  | expr_par}

int = @{ ("-")* ~ ASCII_DIGIT+ }

expr_par = {"(" ~ expr ~")"}


decl = { "var" ~ nom_var ~  "=" ~ expr ~ ";" }
    nom_var = @{ ASCII_ALPHA_LOWER+ }

inst = { decl }

bloque = _{ (inst)* ~ inst?}

prog = _{
    SOI ~
    bloque ~
    EOI
}


